# Generated by Django 2.1 on 2022-05-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_name', models.CharField(max_length=255, null=True)),
                ('retailer_email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('user_email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Retailer')),
            ],
        ),
    ]
