# Generated by Django 2.1 on 2022-05-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='location',
            field=models.CharField(choices=[('Busia', 'Busia'), ('Kisumu', 'Kisumu'), ('Nairobi', 'Nairobi'), ('Kisii', 'Kisii'), ('Nakuru', 'Nakuru')], max_length=255, null=True),
        ),
    ]
