# Generated by Django 2.1 on 2022-05-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=150, unique=True)),
                ('actual_price', models.CharField(max_length=255, null=True)),
                ('offer_price', models.IntegerField(null=True)),
                ('description', models.DateField(auto_now_add=True, null=True)),
                ('retailer', models.ManyToManyField(null=True, to='Account.Retailer')),
            ],
        ),
    ]
