# Generated by Django 2.1 on 2022-05-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='retailer',
            field=models.ManyToManyField(to='Account.Retailer'),
        ),
    ]
